// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbTaTJDA4nsTfMmyiBw6uR_FmRhwcKBYk',
    appId: '1:281995705014:web:21fcc10018d0f818728417',
    messagingSenderId: '281995705014',
    projectId: 'kasby-investment-app',
    authDomain: 'kasby-investment-app.firebaseapp.com',
    storageBucket: 'kasby-investment-app.firebasestorage.app',
    measurementId: 'G-E0VF5E2XHS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRHbxbKco8Sj-mXvb1fmpXUoReU9kgR08',
    appId: '1:281995705014:android:f153b4ca2023d376728417',
    messagingSenderId: '281995705014',
    projectId: 'kasby-investment-app',
    storageBucket: 'kasby-investment-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjt92O2NpesCATTAzXc61peHdhKAq0Cag',
    appId: '1:281995705014:ios:d29934b2556da0c6728417',
    messagingSenderId: '281995705014',
    projectId: 'kasby-investment-app',
    storageBucket: 'kasby-investment-app.firebasestorage.app',
    iosBundleId: 'com.kasby.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjt92O2NpesCATTAzXc61peHdhKAq0Cag',
    appId: '1:281995705014:ios:d29934b2556da0c6728417',
    messagingSenderId: '281995705014',
    projectId: 'kasby-investment-app',
    storageBucket: 'kasby-investment-app.firebasestorage.app',
    iosBundleId: 'com.kasby.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbTaTJDA4nsTfMmyiBw6uR_FmRhwcKBYk',
    appId: '1:281995705014:web:ab81dafcf1c10548728417',
    messagingSenderId: '281995705014',
    projectId: 'kasby-investment-app',
    authDomain: 'kasby-investment-app.firebaseapp.com',
    storageBucket: 'kasby-investment-app.firebasestorage.app',
    measurementId: 'G-CVW33FBZJ9',
  );

}